    base: &base
      adapter: mysql
      socket: /tmp/mysql.sock
      username: golden
      password: random

    development:
      database: gc_development
      <<: *base

    test:
      database: gc_test
      <<: *base

    production:
      database: gc_production
      <<: *base
      
    profile:
      database: gc_production
      <<: *base
